CRUD_imagenes/mysiteTut - solo inserta registros e imagenes/mysiteTut/gallery/urls.py
from django.urls import path
from . import views
app_name = 'gallery'
urlpatterns = [
    path('upload_image/', views.upload_image, name='upload_image'),
    path('image_gallery/', views.image_gallery, name='image_gallery')
]

CRUD_imagenes/mysiteTut - solo inserta registros e imagenes/mysiteTut/mysiteTut/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('gallery/', include(('gallery.urls','gallery'))),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)




    
    

CRUD_imagenes/mysiteTut - solo inserta registros e imagenes/mysiteTut/gallery/models.py
from django.db import models
# Create your models here.

class Image(models.Model):
    image = models.ImageField(upload_to = 'gallery', default='gallery/static/images/no-img.jpg')
    name = models.CharField(max_length=200)
    

CRUD_imagenes/mysiteTut - solo inserta registros e imagenes/mysiteTut/gallery/forms.py
from django import forms
from .models import *
class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ['image','name']

CRUD_imagenes/mysiteTut - solo inserta registros e imagenes/mysiteTut/gallery/views.py
from django.shortcuts import render
from .models import *
from .forms import *
from django.http import HttpResponseRedirect
# Create your views here.

def upload_image(request):
    if request.method == 'GET':
        return render(request, 'upload_image.html')
    elif request.method == 'POST':
        form = ImageForm(request.POST, request.FILES)
        if form.is_valid():
            new_image = Image(  image = form.cleaned_data["image"], name = form.cleaned_data["name"] )
            new_image.save()
            return HttpResponseRedirect('/gallery/image_gallery/')
            #return HttpResponseRedirect('/gallery/upload_image/')


def image_gallery(request):
    images = Image.objects.all()
    print(images)
    return render(request, 'image_gallery.html', {'images': images})

CRUD_imagenes/mysiteTut - solo inserta registros e imagenes/mysiteTut/gallery/templates/image_gallery.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Image Gallery</title>
  </head>
  <body>
    {% load static %}
    {% for image in images %}
      <img src="{{image.image.url}}" alt="{{image.name}}" style="width:150px;">
      <p>{{image.name}}</p>
    {% endfor %}
  </body>
</html>

CRUD_imagenes/mysiteTut - solo inserta registros e imagenes/mysiteTut/gallery/templates/upload_image.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Upload Image</title>
  </head>
  <body>
    <form action="{% url 'gallery:upload_image' %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <p>
          <input id="id_image" type="file" accept="image/*" name="image" required>
      </p>
      <p>
          Image name:
          <input id="id_name" type="text" name="name" required>
      </p>
      <input type="submit" value="Submit" />
    </form>
  </body>
</html>